const constants = {
  CHANGE_TABLE_TITLE: 'CHANGE_TABLE_TITLE',
  CHANGE_SHOW_COUNT: 'CHANGE_SHOW_COUNT',
  UPDATE_TABLE_DATA: 'UPDATE_TABLE_DATA',
  UPDATE_LOADING_FLAG: 'UPDATE_LOADING_FLAG'
};

export default constants;
